version: '3'

services:
  inbound:
    image: nhsdev/nia-mhs-inbound:1.3.3
    ports:
      - "9787:80"
    environment:
      - MHS_LOG_LEVEL=DEBUG
      - MHS_SECRET_PARTY_KEY=VND3J-823806
      - MHS_SECRET_CLIENT_CERT=${MHS_SECRET_CLIENT_CERT}
      - MHS_SECRET_CLIENT_KEY=${MHS_SECRET_CLIENT_KEY}
      - MHS_SECRET_CA_CERTS=${MHS_SECRET_CA_CERTS}
      - MHS_INBOUND_QUEUE_BROKERS=amqp://localhost:5672
      - MHS_INBOUND_QUEUE_NAME=inbound
      - MHS_SECRET_INBOUND_QUEUE_USERNAME=guest
      - MHS_SECRET_INBOUND_QUEUE_PASSWORD=guest
      - MHS_STATE_TABLE_NAME=mhs_state
      - MHS_SYNC_ASYNC_STATE_TABLE_NAME=sync_async_state
      - MHS_DB_ENDPOINT_URL=http://localhost:8000
      - MHS_INBOUND_QUEUE_MESSAGE_TTL_IN_SECONDS=0
      # boto3 requires some AWS creds to be provided, even
      # when connecting to local DynamoDB
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - MHS_INBOUND_USE_SSL=false
      #      - TCP_PORTS=443
      - SERVICE_PORTS=80
      - SUPPORTED_FILE_TYPES
  outbound:
    image: nhsdev/nia-mhs-outbound:1.3.3
    ports:
      - "32768:80"
    environment:
      - MHS_LOG_LEVEL=DEBUG
      - MHS_SECRET_PARTY_KEY=VND3J-823806
      - MHS_SECRET_CLIENT_CERT=-----BEGIN CERTIFICATE-----
        MIIE5DCCA8ygAwIBAgIRAIMzY0v3bf5i/ydIEFfrzT0wDQYJKoZIhvcNAQELBQAw
        TDELMAkGA1UEBhMCR0IxDDAKBgNVBAoTA25oczELMAkGA1UECxMCQ0ExIjAgBgNV
        BAMTGU5IUyBJTlQgQXV0aGVudGljYXRpb24gRzIwHhcNMjQwODI5MTIzNzU3WhcN
        MjcwODI5MTMwNzU3WjBRMQwwCgYDVQQKEwNuaHMxEDAOBgNVBAsTB0RldmljZXMx
        LzAtBgNVBAMTJmludHRpZi5jaGVja3VwaGVhbHRoLnRoaXJkcGFydHkubmhzLnVr
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv3pXb3aYYD26nxXDBJqK
        Jte94O6bc+4hzMbwF8BAc9fqGP1goDrf/QwFGC1pKY1+zWzLpOm4mdj0C38ll48Y
        +Tis1u+m6qGZ29pGKAbkGMfjY94YTQt0J68W58eyM8yv6gjWvkszlW1Y33jj08ul
        SInBDC46eRmHMif3NYLGT8AEsbC6O9YngG4stfJv8IIg72PnUPGIzepPmcbK0a44
        8he4gjhXTIPAuEXbc+4pNk0ZbaxNQJ4JGVVeBDrHSX3w25X8Sw+Kr1XUVsC3c6DI
        daXPU43Zl8qwLrbH3uTTkfkW33x0gEVxVuX2+8SNWPwdRpkgRTAgAvrolEL14WmX
        KwIDAQABo4IBujCCAbYwCwYDVR0PBAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMB
        BggrBgEFBQcDAjBvBggrBgEFBQcBAQRjMGEwIwYIKwYBBQUHMAGGF2h0dHA6Ly9v
        Y3NwLm5ocy51ay9vY3NwMDoGCCsGAQUFBzAChi5odHRwOi8vcGtpLm5ocy51ay9p
        bnQvRzIvYXV0aC9OSFNJTlRBdXRoRzIuY3J0MD4GA1UdIAQ3MDUwMwYLKoY6AIl7
        ZQADAgAwJDAiBggrBgEFBQcCARYWaHR0cHM6Ly9wa2kubmhzLnVrL0NQUzBDBgNV
        HR8EPDA6MDigNqA0hjJodHRwOi8vY3JsLm5ocy51ay9pbnQvZzIvYXV0aC9OSFNJ
        TlRhdXRoRzJfYzIwLmNybDArBgNVHRAEJDAigA8yMDI0MDgyOTEyMzc1N1qBDzIw
        MjYxMDA1MDEwNzU3WjAfBgNVHSMEGDAWgBQWx0cEqGDJ5F2rmfKU98PeM5jUIjAd
        BgNVHQ4EFgQUbsMArmsnKZWDE4Daqn7xF/PgGfMwCQYDVR0TBAIwADAaBgkqhkiG
        9n0HQQAEDTALGwVWMTAuMAMCBLAwDQYJKoZIhvcNAQELBQADggEBAH0FQTh/IZLV
        kOK01Maw6aCeg3/1jks1RhIBAVK2OVoB0Fe3q4Dx/rFnqjWmIypyOrCWe6Av1RJD
        j4f2f8tIRCUnINXQLLa5hA6L8QcCqSf92vPQegGE6RPGoyY3Z67xXDW0JjKhNfZk
        8Jee3Py+XEYu1nxMkZAc0sewiPm4bbgiL/YtBVycGLR3OG++5Y+fWMGLd9Kjr6cQ
        MaMVqxifurPZYqrja0XwFGnU3fFeT73cRGlym3TrCDrpWatsDQquIXtJAU7y+1K0
        ENHrdjPazyJryo2EH7yGZCSD9GukcETIPjzAsxiN+fjfXoC2FaOHynWp7ikoaCv1
        jN8AbCnViNM=
        -----END CERTIFICATE-----
      - MHS_SECRET_CLIENT_KEY=-----BEGIN PRIVATE KEY-----
        TUlJRXZRSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2N3Z2dTakFnRUFBb0lC
        QVFDL2VsZHZkcGhnUGJxZg0KRmNNRW1vb20xNzNnN3B0ejdpSE14dkFYd0VCejEr
        b1kvV0NnT3QvOURBVVlMV2twalg3TmJNdWs2YmlaMlBRTA0KZnlXWGp4ajVPS3pX
        NzZicW9abmIya1lvQnVRWXgrTmozaGhOQzNRbnJ4Ym54N0l6eksvcUNOYStTek9W
        YlZqZg0KZU9QVHk2VklpY0VNTGpwNUdZY3lKL2MxZ3NaUHdBU3hzTG83MWllQWJp
        eTE4bS93Z2lEdlkrZFE4WWpONmsrWg0KeHNyUnJqanlGN2lDT0ZkTWc4QzRSZHR6
        N2lrMlRSbHRyRTFBbmdrWlZWNEVPc2RKZmZEYmxmeExENHF2VmRSVw0Kd0xkem9N
        aDFwYzlUamRtWHlyQXV0c2ZlNU5PUitSYmZmSFNBUlhGVzVmYjd4STFZL0IxR21T
        QkZNQ0FDK3VpVQ0KUXZYaGFaY3JBZ01CQUFFQ2dnRUFJTGVJeFJUZ2lHRkR4L2J4
        OFpGdVZhQzdZdm1pT2piUU02c3lUdnljaHE2Mw0KNHprNEQyaS82UDdxeCt6S2NU
        MHFFM09wZ0M0blNySlZVTG1TOU1pUW5kVGZRNEtEWk1ma0FEclZqZlZQZUNSLw0K
        YUFzRTMvVTdEYVRQSng5cUJZdk42eEZEa0JSTlpoVGZBS0FwWFlFSVp0S1MxNy8y
        WWNiSTRQc1BOR2Q1OXhvdQ0KZGY3emdiZDZTQTQ3cEFIb3JlZ2VhUmNzTUl6dHF0
        amYzVWhZZTRXb3FIWkZLVXZUa3hnUGJzN0UxcDVUWjkyZw0KUnNsVGREYlFxTGFI
        ZGlUT3FLQi9nMzYzcWhKNWRWVm0rcmI2TWp0Z0pHZG5wTFZINVh4dWJvRUNYRjRG
        UkpSMw0KU3RyTTJIR1NCMXo3WmVhc05pS3RUNjNrTU83UUtpQTVUeWx0endITTBR
        S0JnUURucy8zYk5xWWZ1aFdDZHZ3cQ0KVzBvT045T0tBQnlXUkl1d1d6SVFXSVFV
        bTJzendIMmZnVUpCMlYzL0FYRC95MlNFZFFaTTNBMEwweEJoVlRRag0KY2MybnZM
        N3A2SitvaVlwMkdVSG03M3RIcGtBenE3aGJBNkFOUkdSbVJEMnBJVWpPTDVxUGJ0
        d00rZ2ZHVHBjTg0KbWpVWUdmdzFnZ2swTE9aSG4rNHNTVkFObndLQmdRRFRqb1Bo
        UHRJMU84dXA5MU5CYlNYZVNwM3FNV1VhOWR0Sw0KZUxCOHdFS0NCV2RsRkwwZkQx
        aE1qbUpFcWFZNFVabTFHcy9zYkRJa0dvZ2FobXNTNmxFaVRXRmJFSzZnRlVUWQ0K
        ZENKNjVXaHVxZExLeXZrd21yNDY5NEN0cDZFamhib2QvMi8yR0JQaFdMclVUQVFT
        WjRUSDhacC9LSlpTWHNnbA0KNGpWTzZTeXk5UUtCZ1FEWGhJMUkvUkVTaThUOElH
        NjNlMGhyNXpPRnRrcmczd3RMMDlmQ2FvTVlvK1BZTkdEbA0KSDVjZ3B1NE9oeW16
        VkYyLzh4WVVJYzZreEFNRmRmcFVTY093RlJsRGUxUWVzU2l3Wnhmc2xhOEcyelgy
        bWZDVg0KLzg0ODZQTzJTQjFPbHg0Z1l4a1I5MTBKV1B3b1VldWhCR0lFZEE4ck9q
        UVRhdndiZlVCTnd6ZUtJd0tCZ0ZrYQ0KbG50QmJXSVVmRlJySWpyVlVQVE9jcktY
        K1dDZ21xdEVKL2x6Tk0vMG5MYmJSRWlYdXZZTHBtSUxIa0pzUkJRZQ0KWmVMTE0x
        YzNnWW5DZ2NpbXZtTjNPZ0VVQnFqUUxINEtkQmRWRm1ZOXl0VzFKYjJOLzM5d2pW
        Y1cybXpPdnpReA0KU1NQYXdrelFoV2d6V0NlMFNCMjZxZnJTeW5XSkREM0FoL2xq
        aG5zZEFvR0FhQ0RsWi9OL0JQdk1XZmFmeUdYZw0KWnIxaUVzbzNWenVscjMvVXdh
        c3FkYlVSVktiZ2xoV3pkVHVaTXdpUGpoYnJWY1BEWnpwZzAydUhITTdVWHRCSQ0K
        ZzgzbXowbWFlZzFjUkU2ZnRWTVJRVUxjcmRGMWhKNDRkYjBvSGJBN0ZST0RCSmhJ
        YXpQdExQVkFYWStqNTdLQQ0KMXZzaVdNdVNxbVBSYkw1eWlhWTJRVmM9
        -----END PRIVATE KEY-----
      - MHS_SECRET_CA_CERTS=-----BEGIN CERTIFICATE-----
        MIIFhzCCA2+gAwIBAgIQGjdQ3OTSYx62oSmGTy9tazANBgkqhkiG9w0BAQwFADBM
        MQswCQYDVQQGEwJHQjEMMAoGA1UEChMDbmhzMQswCQYDVQQLEwJDQTEiMCAGA1UE
        AxMZTkhTIFBUTCBSb290IEF1dGhvcml0eSBHMjAeFw0yMjA4MDQxNDA1NDNaFw0z
        MjA4MDQxNDM1NDNaMEwxCzAJBgNVBAYTAkdCMQwwCgYDVQQKEwNuaHMxCzAJBgNV
        BAsTAkNBMSIwIAYDVQQDExlOSFMgSU5UIEF1dGhlbnRpY2F0aW9uIEcyMIIBIjAN
        BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxT9GjD+It1PZUGSCxqgZl0GFu1Bs
        T2+IrzTQP0PnI0GQSEVmln4629ezXxhPigPqokzw4lDS/x5a/1qcSVMzgPBkaYH8
        04+MEBQNatuZhEu6zJPr6ARR3kGEf6MfxyllL5FwxU7AYNuACb6eVKvST/OC40Vx
        CGEhoIwvhvA016K50wYwtv8oiaywpHx+NbD2VhdOOsHNHZIauOmqHzY3IwmvS5NA
        NiZx8s8ctETbRsrwgO3p/667ix3PZME9yCPmzhm9TsyJABEjIDrRm1qW15V+GNfz
        jjBkN+j5dmtJRHbO+KLwwqY63sHg3JNeA74FFxxfVlSwUykeuQTT8UbcbwIDAQAB
        o4IBYzCCAV8wDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwPgYD
        VR0gBDcwNTAzBgsqhjoAiXtlAAMCADAkMCIGCCsGAQUFBwIBFhZodHRwczovL3Br
        aS5uaHMudWsvQ1BTMHgGCCsGAQUFBwEBBGwwajAjBggrBgEFBQcwAYYXaHR0cDov
        L29jc3AubmhzLnVrL29jc3AwQwYIKwYBBQUHMAKGN2h0dHA6Ly9wa2kubmhzLnVr
        L1BUTC9HMi9yb290L05IU1BUTFJvb3RBdXRob3JpdHlHMi5jcnQwPwYDVR0fBDgw
        NjA0oDKgMIYuaHR0cDovL2NybC5uaHMudWsvUFRML0cyL3Jvb3QvTkhTUFRMcm9v
        dEcyLmNybDAfBgNVHSMEGDAWgBT1ttVSqL14/nJhaztdjCPAsBYM8zAdBgNVHQ4E
        FgQUFsdHBKhgyeRdq5nylPfD3jOY1CIwDQYJKoZIhvcNAQEMBQADggIBAEWWjN0d
        6uxtKi5aLEv0CtUXqg7MJClCHKwCpYuewzI/OfRux5LuL7xHQx8Baj5Jh2IiZLkc
        vPQ626RVnKaYOvJAoM7UWMFgr3vta0uMEAnxRIOCpNiQFDh4HBpzbQNcMg8zkKUi
        JMb4OmT09zCzGTG2WdPT6KwAJOXw9IVeT+Z8ggScCmbiLKHT+s9y612oekIH0SxM
        /BNjmyYWt02cON6e92XXs6refjoJS29Kne2nBwersk1bLAumcueVBEtnMUBILXlH
        XoFcCIZSOca/qg9K7jyxl+uyXWK74AblMi0RfKsziM34Ux+hKv03SknLT9kbIBt0
        lbjntoeweu4oXMDQ+wdjSRe0OM0Ed2ttFMsI8jSkJAQlvN1uks5/M+cdAsg3D7Gp
        Df3WPHCT17ulr9VJ5I16XOb6JnNoMGEgUQm/AyNGO2zLm+XLo4Ujk/dKES08Cwwm
        zjXqOCti2Kp9mWYF8x1gOwIu4ye+rBhJdlNnxvbdV4oOyo1CYyw261jWI19yCaDJ
        Hmgq1F8M7nY0C9NRqlRaB1G+p1+mZVlVMOOD6EmprV80rBDfVN/N2swbmSGhijNe
        zAlqBMIkp6jTG9lEJbvtpY6aGWGlEheb2pPcBCXcBknI1Lhqv/sgdM6zbkzD+rAi
        oukkF6E6wLgCHgPz3FJwVBnM0NdaISHTBbOQ
        -----END CERTIFICATE-----
        -----BEGIN CERTIFICATE-----
        MIIFtDCCA5ygAwIBAgIQHJP1UsE9cdiw+4IqFnxM3TANBgkqhkiG9w0BAQwFADBM
        MQswCQYDVQQGEwJHQjEMMAoGA1UEChMDbmhzMQswCQYDVQQLEwJDQTEiMCAGA1UE
        AxMZTkhTIFBUTCBSb290IEF1dGhvcml0eSBHMjAeFw0yMjA4MDIxNTE3MjRaFw00
        MjA4MDIxNTQ3MjRaMEwxCzAJBgNVBAYTAkdCMQwwCgYDVQQKEwNuaHMxCzAJBgNV
        BAsTAkNBMSIwIAYDVQQDExlOSFMgUFRMIFJvb3QgQXV0aG9yaXR5IEcyMIICIjAN
        BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAwIy5AVQWAT35rfI0AYCql2F04Yp9
        M6gTgv6vmxtdHsIJgLCrbxy5p6hQIxCu0Jq4Fc8rflv5jDZOPO6tsFRuJck1Xv17
        53jBAuo00Q0XoORdfTymktLp78P2zNvj3Y3oaXUW6dzwztQf/BLjSwD0A3uuiej8
        BuemHDQDCWHhfu8fkVC85n8XPO1QKzmpTHXBK5tgx5SkDzfxk3zsc31tgs+/xRmZ
        Jc45qWQazFCtGr5rpeKb/9thi9+LbctCMO2Be4La4u6rePOhR8zx73zpLnrtOD8s
        Nfxqk59vyIZ7fqfGCfIs8hdcQFOvfABalSaW2Bg4njwOY879WjyxtE1jpPB/fuDp
        /cQtrdNVLEY+fEa+WBbX/TG2GAQFFle/ThU+c2mtkfToRL42Hrbzfqg9wr69e2oI
        79cQ3DKP1Eaq0bzw8TkOfswoKgKm4QGlBzJFAWaAEvisX+JgRtPzvSTMCttUbBYp
        NnfXwayQ8s9IwYwPeFDQrs0/MR+uUqtObUv9B3T4bNBXoIc98rn7+/x5yQhGYre8
        0YzcqeL33A/K6Tzu+P3u9DftfkOgcnZyg69ePqAAjrY9OA2RqnVfxm7vraaEgxMm
        rpslCni/FM+/P6yV4LdnDJuKfaMq0k+RfkbsT2WXsJHLIec8uRgpoa74QvEO/p85
        UDIFBUds0QqN1GsCAwEAAaOBkTCBjjAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH/
        BAUwAwEB/zArBgNVHRAEJDAigA8yMDIyMDgwMjE1MTcyNFqBDzIwNDIwODAyMTU0
        NzI0WjAfBgNVHSMEGDAWgBT1ttVSqL14/nJhaztdjCPAsBYM8zAdBgNVHQ4EFgQU
        9bbVUqi9eP5yYWs7XYwjwLAWDPMwDQYJKoZIhvcNAQEMBQADggIBAKekcO9zq3ER
        YFOJTDqkY4NoDSTmlab4Al07hLJ8WYckSePQ9HmxVEqnTVYBCtPHfcyUlUqbBQVh
        DBQ2ZzERONqq2ENevGh6Li/0ZxuPiQhb5hxL7uv20vTEmbkSrPYs5TKYNbkJ8gx+
        JT4uoxETLfNHG6WvGV2VBbMR+dZQisRoR0jm8P7n7wkTHjiDNH7FLfgozy3hIfUR
        0bhLEt3HlniPBoC4egvZMP/R8rnOwqdEmStP6YR2BZxUSmrQozOamVJIljMTiTlG
        xwqmvVMnRtaYIQsdOyiXpS4UjocbebV+a7u9Bbst/Y2rV8PVprpATlqj4YOjqrNx
        v5MrLgyknNKUIqhbJXAy9j74x8OO1tilH6vf32zapZa/GtHpTvo7nRr1pNnfUgbp
        vBCvXoxIrg7rrWx3kjRF9Cri1d5khUDXYJzewflSsgYLLTygQ+lwthw+XghdHNos
        TARNSRPrO5JsWmSc6R9bjcuyhAsxvhAS1LpE1EwckkMUgSvdfmKbNc3RkjyusGYP
        Nlo+MiECpArwqymOxnULpKCwgJApVrwht0eDYzIw5XCe68FCQ/Ewaj25l81gVyWQ
        gM4KvdmCt0vk++15mcuUayTdcUg4cAGegvP8g0a9qncHT83J9E4D47QvftZkqZtF
        E3e+hb4BEdtJoedF9IHxjaHpRVhwJT98
        -----END CERTIFICATE-----
      - MHS_STATE_TABLE_NAME=mhs_state
      - MHS_DB_ENDPOINT_URL=http://host.docker.internal:8000
      - MHS_SYNC_ASYNC_STATE_TABLE_NAME=sync_async_state
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - MHS_RESYNC_INTERVAL=1
      - MAX_RESYNC_RETRIES=20
      - MHS_SPINE_ROUTE_LOOKUP_URL=http://localhost:8080/route
      - MHS_SPINE_ORG_CODE=YES
      - MHS_SPINE_REQUEST_MAX_SIZE=4999600 # 5 000 000 - 400
      # Note that this endpoint URL is Opentest-
      - MHS_FORWARD_RELIABLE_ENDPOINT_URL=https://msg.int.spine2.ncrs.nhs.uk/reliablemessaging/reliablerequest
      # This is for disabling hostname validation so OpenTest ip address
      - MHS_OUTBOUND_VALIDATE_CERTIFICATE=${MHS_OUTBOUND_VALIDATE_CERTIFICATE:-True}
      - SERVICE_PORTS=80
      - MHS_OUTBOUND_ROUTING_LOOKUP_METHOD=SDS_API
      - MHS_SDS_API_URL=https://int.api.service.nhs.uk/spine-directory/FHIR/R4
      - MHS_SDS_API_KEY=BGH3LMDtnadxNtL6YetqurpZDnE4wjtz
  route:
    image: nhsdev/nia-mhs-route:1.3.3
    ports:
      - "8080:80"
    environment:
      - MHS_LOG_LEVEL=NOTSET
      - MHS_SDS_URL=ldap://192.168.128.11
      - MHS_SDS_SEARCH_BASE=ou=services,o=nhs
      - MHS_DISABLE_SDS_TLS=True
      - MHS_SDS_REDIS_CACHE_HOST=redis
      - MHS_SDS_REDIS_DISABLE_TLS=True
  dynamodb:
    container_name: host.docker.internal
    image: nhsdev/nia-dynamodb-local:latest
    ports:
      - "8000:8000"
  mongodb:
    image: mongo:5.0.16
    ports:
      - "27018:27018"
  rabbitmq:
    image: nhsdev/nia-rabbitmq-local:latest
    ports:
      - "15672:15672"
      - "5672:5672"
    hostname: "localhost"
  redis:
    image: redis
    ports:
      - "6379:6379"

  inbound-lb:
    image: dockercloud/haproxy
    links:
      - inbound
    ports:
      - "443:443"
      - "8079:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MODE=tcp
      - TIMEOUT=connect 0, client 0, server 0

  outbound-lb:
    image: dockercloud/haproxy
    links:
      - outbound
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TIMEOUT=connect 0, client 0, server 0

  sds-api-mock:
    build: ./docker/sds-api-mock
    ports:
      - "8081:8080"
    command:
      - -global-response-templating
      - --verbose